import {beforeEach,describe,expect,it,vi} from "vitest";
vi.mock("server-only",()=>({}));

const mocks=vi.hoisted(()=>({gmailSend:vi.fn(),draftCreate:vi.fn(),driveList:vi.fn(),driveCreate:vi.fn(),peopleSearch:vi.fn(),peopleCreate:vi.fn(),calendarInsert:vi.fn()}));
vi.mock("googleapis",()=>({google:{auth:{OAuth2:class{setCredentials(){}}},gmail:()=>({users:{messages:{send:mocks.gmailSend},drafts:{create:mocks.draftCreate}}}),drive:()=>({files:{list:mocks.driveList,create:mocks.driveCreate}}),people:()=>({people:{searchContacts:mocks.peopleSearch,createContact:mocks.peopleCreate}}),calendar:()=>({events:{insert:mocks.calendarInsert}})}}));
import {createCalendarFollowup,createGmailDraft,findGoogleContactByEmail,sendGmail,uploadBusinessCard} from "../src/lib/google";

beforeEach(()=>{vi.clearAllMocks();Object.assign(process.env,{GOOGLE_CLIENT_ID:"client",GOOGLE_CLIENT_SECRET:"secret",GOOGLE_REDIRECT_URI:"https://app.example.jp/api/google/oauth/callback",GOOGLE_REFRESH_TOKEN:"refresh",GOOGLE_SHARED_GMAIL:"club@example.jp",GOOGLE_DRIVE_FOLDER_ID:"root",GOOGLE_CALENDAR_ID:"primary"})});
describe("Google server boundaries",()=>{
  it("sends and drafts only one MIME message through Gmail",async()=>{mocks.gmailSend.mockResolvedValue({data:{id:"m1"}});mocks.draftCreate.mockResolvedValue({data:{id:"d1"}});await sendGmail("to@example.jp","御礼","本文");await createGmailDraft("to@example.jp","御礼","本文");expect(mocks.gmailSend).toHaveBeenCalledOnce();expect(mocks.draftCreate).toHaveBeenCalledOnce();expect(mocks.gmailSend.mock.calls[0][0].requestBody.raw).toBeTruthy()});
  it("creates the Drive year/month path and uploads one image",async()=>{mocks.driveList.mockResolvedValue({data:{files:[]}});mocks.driveCreate.mockResolvedValueOnce({data:{id:"cards"}}).mockResolvedValueOnce({data:{id:"year"}}).mockResolvedValueOnce({data:{id:"month"}}).mockResolvedValueOnce({data:{id:"file",name:"card.jpg"}});await uploadBusinessCard(Buffer.from("image"),"card.jpg","image/jpeg");expect(mocks.driveList).toHaveBeenCalledTimes(3);expect(mocks.driveCreate).toHaveBeenCalledTimes(4)});
  it("detects an existing People contact by exact normalized email",async()=>{mocks.peopleSearch.mockResolvedValueOnce({data:{results:[]}}).mockResolvedValueOnce({data:{results:[{person:{resourceName:"people/1",emailAddresses:[{value:"Person@Example.jp"}]}}]}});expect((await findGoogleContactByEmail("person@example.jp"))?.resourceName).toBe("people/1")});
  it("creates Calendar events only through an explicit call without invitations",async()=>{mocks.calendarInsert.mockResolvedValue({data:{id:"event-1"}});await createCalendarFollowup({summary:"連絡",description:"確認",start:"2026-09-16T01:00:00.000Z",end:"2026-09-16T01:30:00.000Z"});expect(mocks.calendarInsert).toHaveBeenCalledWith(expect.objectContaining({sendUpdates:"none",calendarId:"primary"}))});
  it("never exposes mailbox synchronization helpers",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../src/lib/google.ts",import.meta.url),"utf8"));expect(source).not.toContain("messages.list");expect(source).not.toContain("threads.list");expect(source).not.toContain("gmail.readonly")});
});
