"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowRight,Building2,Hash,LogIn,ShieldCheck,UserPlus,Users} from "lucide-react";
import {appFetch} from "@/lib/client-api";
import {createClient} from "@/lib/supabase/browser";

type Intent="member"|"create"|null;
type Status={authenticated:boolean;email:string;hasMembership:boolean;membershipStatus:string|null;membershipMessage:string|null;member:{name:string;access_role:string;club:{name:string}|null}|null};

export default function StartPage(){
  const router=useRouter();
  const [intent,setIntent]=useState<Intent>(null),[email,setEmail]=useState(""),[status,setStatus]=useState<Status|null>(null),[checking,setChecking]=useState(true),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [organizationName,setOrganizationName]=useState(""),[organizationType,setOrganizationType]=useState<"university_club"|"student_organization"|"other">("university_club"),[ownerName,setOwnerName]=useState(""),[ownerTitle,setOwnerTitle]=useState("");
  const [inviteCode,setInviteCode]=useState(""),[joinName,setJoinName]=useState(""),[joinTitle,setJoinTitle]=useState("");

  async function refreshStatus(){setChecking(true);try{const {data:{session}}=await createClient().auth.getSession();if(!session){setStatus(null);return}setStatus(await appFetch<Status>("/api/onboarding/status"))}catch(error){setMessage(error instanceof Error?error.message:"ログイン状態を確認できませんでした。")}finally{setChecking(false)}}
  async function sendLoginLink(nextIntent:Exclude<Intent,null>){setBusy(true);setMessage("");try{const {error}=await createClient().auth.signInWithOtp({email,options:{shouldCreateUser:true,emailRedirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent(`/start?intent=${nextIntent}`)}`}});if(error)throw error;setMessage(nextIntent==="create"?"団体作成用の認証リンクを送信しました。メールを開いてください。":"部員ログイン用のリンクを送信しました。メールを開いてください。")}catch(error){setMessage(loginErrorMessage(error))}finally{setBusy(false)}}
  async function createOrganization(){setBusy(true);setMessage("");try{await appFetch("/api/onboarding/organization",{method:"POST",body:JSON.stringify({organizationName,organizationType,ownerName,ownerTitle})});router.push("/settings?onboarding=complete");router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"団体を作成できませんでした。")}finally{setBusy(false)}}
  async function joinOrganization(){setBusy(true);setMessage("");try{const result=await appFetch<{ok:boolean;organizationName:string}>("/api/onboarding/join",{method:"POST",body:JSON.stringify({inviteCode,name:joinName,title:joinTitle})});setMessage(`${result.organizationName} に入部を申請しました。代表または幹部の承認をお待ちください。`);await refreshStatus()}catch(error){setMessage(error instanceof Error?error.message:"参加できませんでした。")}finally{setBusy(false)}}
  async function signOut(){await createClient().auth.signOut();setStatus(null);setIntent(null);setMessage("")}
  useEffect(()=>{const timer=setTimeout(()=>{const requested=new URL(window.location.href).searchParams.get("intent");if(requested==="member"||requested==="create")setIntent(requested);void refreshStatus()},0);return()=>clearTimeout(timer)},[]);

  if(checking)return <StartFrame><p className="py-20 text-center text-sm font-bold text-[#68746d]">ログイン状態を確認しています…</p></StartFrame>;
  if(status&&!status.hasMembership&&(status.membershipStatus==="pending"||status.membershipStatus==="suspended"))return <StartFrame><section className="rounded-[28px] border border-[#cfe0d5] bg-white p-6 shadow-sm"><span className="grid size-12 place-items-center rounded-2xl bg-[#fff6df] text-[#a25c00]"><ShieldCheck/></span><h1 className="mt-4 text-2xl font-black">{status.membershipStatus==="pending"?"入部の承認待ちです":"利用が一時停止されています"}</h1><p className="mt-2 text-sm leading-6 text-[#68746d]">{status.membershipMessage}</p><button className="btn-primary mt-6 w-full" disabled={checking} onClick={()=>void refreshStatus()}>状態を再確認</button><button className="mt-3 w-full text-sm font-bold text-[#68746d] underline" onClick={signOut}>別のアカウントを使う</button></section></StartFrame>;
  if(status?.hasMembership)return <StartFrame><section className="rounded-[28px] border border-[#cfe0d5] bg-white p-6 shadow-sm"><span className="grid size-12 place-items-center rounded-2xl bg-[#e2f2e8] text-[#176b45]"><ShieldCheck/></span><h1 className="mt-4 text-2xl font-black">ログイン済みです</h1><p className="mt-2 text-sm text-[#68746d]">{status.member?.club?.name??"所属団体"}・{status.member?.name}さん</p><Link className="btn-primary mt-6 w-full" href="/">アプリを開く<ArrowRight size={18}/></Link><button className="mt-3 w-full text-sm font-bold text-[#68746d] underline" onClick={signOut}>別のアカウントを使う</button></section></StartFrame>;
  if(status&&!status.hasMembership&&intent==="create")return <StartFrame><section className="rounded-[28px] border border-[#cfe0d5] bg-white p-6 shadow-sm"><p className="eyebrow">Create organization</p><h1 className="mt-1 text-2xl font-black">新しい団体を作る</h1><p className="mt-2 text-sm text-[#68746d]">{status.email} を最初のownerとして登録します。</p><div className="mt-6 grid gap-4"><label className="label">団体名<input className="field" value={organizationName} onChange={e=>setOrganizationName(e.target.value)} placeholder="例：○○大学 起業部"/></label><label className="label">団体種別<select className="field" value={organizationType} onChange={e=>setOrganizationType(e.target.value as typeof organizationType)}><option value="university_club">大学・学校の部活／サークル</option><option value="student_organization">学生団体</option><option value="other">その他の団体</option></select></label><label className="label">あなたの氏名<input className="field" value={ownerName} onChange={e=>setOwnerName(e.target.value)} autoComplete="name"/></label><label className="label">役職・肩書<input className="field" value={ownerTitle} onChange={e=>setOwnerTitle(e.target.value)} placeholder="例：代表、部長"/></label><div className="rounded-2xl bg-[#f3f7f4] p-4 text-xs leading-6 text-[#58645d]">作成者は団体のownerになります。作成後、管理者・部員の招待や組織Googleアカウントの設定ができます。</div><button className="btn-primary w-full" disabled={busy||organizationName.trim().length<2||!ownerName.trim()} onClick={createOrganization}>{busy?"作成しています…":"この内容で団体を作る"}</button></div>{message&&<p role="status" className="mt-4 text-sm font-bold text-[#a13b32]">{message}</p>}<button className="mt-4 w-full text-sm font-bold text-[#68746d] underline" onClick={()=>setIntent(null)}>戻る</button></section></StartFrame>;

  return <StartFrame><div className="grid gap-4"><div><p className="eyebrow">Organization CRM</p><h1 className="mt-1 text-3xl font-black tracking-tight">つながりを、団体の力に。</h1><p className="mt-3 text-sm leading-7 text-[#68746d]">参加済みの部員はログイン。最初の幹部は新しい団体を作成してください。</p></div><ChoiceCard icon={LogIn} title="部員としてログイン" description="はじめての人も、ここからメールでログインして組織コードで入部を申請できます。" active={intent==="member"} onClick={()=>{setIntent("member");setMessage("")}}/><ChoiceCard icon={Building2} title="新しい団体を作る" description="代表者として団体を開設し、管理者や部員を招待します。" active={intent==="create"} onClick={()=>{setIntent("create");setMessage("")}}/>{intent&&<section className="rounded-[24px] border bg-white p-5"><h2 className="flex items-center gap-2 font-black">{intent==="member"?<Users size={20}/>:<UserPlus size={20}/>}メールアドレスを確認</h2><p className="mt-2 text-xs leading-5 text-[#68746d]">パスワードは不要です。届いた1回限りのリンクからログインします。</p><input className="field mt-4" type="email" inputMode="email" autoComplete="email" placeholder="you@example.jp" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn-primary mt-3 w-full" disabled={busy||!email.includes("@")} onClick={()=>sendLoginLink(intent)}>{busy?"送信しています…":"認証リンクを送信"}</button></section>}{status&&!status.hasMembership&&intent!=="create"&&<section className="rounded-[24px] border-2 border-[#d4a843] bg-[#fffbf0] p-5"><h2 className="flex items-center gap-2 font-black text-[#765518]"><Hash size={20}/>組織コードで参加</h2><p className="mt-2 text-xs leading-5 text-[#68746d]">{status.email} でログイン済みです。幹部から共有された組織コードを入力して参加してください。</p><input className="field mt-4" placeholder="組織コード（例：AB12CD34）" value={inviteCode} onChange={e=>setInviteCode(e.target.value.toUpperCase())} maxLength={12}/><input className="field mt-2" placeholder="あなたの氏名" value={joinName} onChange={e=>setJoinName(e.target.value)} autoComplete="name"/><input className="field mt-2" placeholder="役職・肩書（任意）" value={joinTitle} onChange={e=>setJoinTitle(e.target.value)}/><button className="btn-primary mt-3 w-full" disabled={busy||inviteCode.length<6||!joinName.trim()} onClick={joinOrganization}>{busy?"参加しています…":"この団体に参加する"}</button><button className="mt-3 w-full text-sm font-bold text-[#68746d] underline" onClick={signOut}>別のアカウントでやり直す</button></section>}{message&&<p role="status" className="rounded-2xl bg-white p-4 text-sm font-bold">{message}</p>}</div></StartFrame>;
}

function ChoiceCard({icon:Icon,title,description,active,onClick}:{icon:typeof LogIn;title:string;description:string;active:boolean;onClick:()=>void}){return <button className={`flex w-full items-center gap-4 rounded-[24px] border-2 p-5 text-left transition ${active?"border-[#176b45] bg-[#f1faf4]":"border-[#dce4de] bg-white"}`} onClick={onClick}><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#e2f2e8] text-[#176b45]"><Icon/></span><span className="flex-1"><strong className="block text-lg">{title}</strong><span className="mt-1 block text-xs leading-5 text-[#68746d]">{description}</span></span><ArrowRight size={20}/></button>}
function StartFrame({children}:{children:React.ReactNode}){return <main className="mx-auto max-w-xl px-4 py-8 md:py-14">{children}</main>}

/** Supabaseの英語のエラーを、部員が読める日本語にする。 */
function loginErrorMessage(error:unknown){
  const text=error instanceof Error?error.message:"";
  if(/after \d+ seconds|rate limit|too many/i.test(text))return "短い時間に何度も送信されました。1分ほど待ってから、もう一度お試しください。";
  if(/invalid.*email|email.*invalid|unable to validate email/i.test(text))return "メールアドレスの形を確認してください。";
  if(/signups? not allowed|signup.*disabled/i.test(text))return "このメールアドレスではログインできません。代表または幹部に確認してください。";
  return "認証リンクを送信できませんでした。少し待ってから、もう一度お試しください。";
}
