"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {Cloud,KeyRound,Link2,LogIn,LogOut,Mail,Save,ShieldCheck,Smartphone,Unlink,UserPlus} from "lucide-react";
import {appFetch,sha256Hex} from "@/lib/client-api";
import {createClientId} from "@/lib/client-crypto";
import {createClient} from "@/lib/supabase/browser";
import {useAppData} from "@/lib/use-app-data";
import type {AccessRole,MailSettings,SenderStatus} from "@/lib/organization-mail";
import {positionLabel,type Position} from "@/lib/membership";
import {MemberRoster,type LibraryRequest,type RosterMember} from "@/components/member-roster";

type Template={id:string;name:string;default_subject:string;default_body:string;is_default:boolean};
type Member=RosterMember;
type Connection={google_email:string;status:string;connected_at:string}|null;
type Settings={member:{id:string;name:string;role:string;signature:string;access_role:AccessRole};sender:SenderStatus;canSuspend:boolean;libraryRequests:LibraryRequest[];organization:{id:string;name:string;invite_code?:string};mailSettings:MailSettings;members:Member[];organizationGoogle:Connection;userGoogle:Connection;oauthClientConfigured:boolean;devices:Array<{device_id_hash:string;label:string;revoked_at:string|null}>;templates:Template[]};
type TemplateForm={id?:string;name:string;subject:string;body:string;isDefault:boolean};
const emptyTemplate:TemplateForm={name:"",subject:"",body:"",isDefault:false};
async function deviceIdentity(){let id=localStorage.getItem("connection-book-device-id");if(!id){id=createClientId();localStorage.setItem("connection-book-device-id",id)}return{id,hash:await sha256Hex(new Blob([id]))}}
const roleLabel:Record<AccessRole,string>={owner:"代表",admin:"幹部",member:"部員"};

export function DeviceSettings(){
 const state=useAppData<Settings>("/api/app?view=settings"),[email,setEmail]=useState(""),[loginMessage,setLoginMessage]=useState(""),[name,setName]=useState(""),[title,setTitle]=useState(""),[signature,setSignature]=useState(""),[deviceId,setDeviceId]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[template,setTemplate]=useState<TemplateForm>(emptyTemplate),[inviteEmail,setInviteEmail]=useState(""),[inviteName,setInviteName]=useState(""),[inviteTitle,setInviteTitle]=useState(""),[inviteRole,setInviteRole]=useState<"admin"|"member">("member"),[organizationName,setOrganizationName]=useState(""),[policy,setPolicy]=useState<MailSettings|null>(null),[twoFaEmail,setTwoFaEmail]=useState(""),[twoFaOtp,setTwoFaOtp]=useState(""),[twoFaSession,setTwoFaSession]=useState(""),[twoFaRegistered,setTwoFaRegistered]=useState<string|null>(null),[twoFaStep,setTwoFaStep]=useState<"idle"|"sending"|"sent"|"verifying">("idle"),[twoFaMsg,setTwoFaMsg]=useState("");const deviceChecked=useRef(false);
 useEffect(()=>{void deviceIdentity().then(x=>setDeviceId(x.id))},[]);
 useEffect(()=>{const result=new URLSearchParams(location.search).get("google");if(!result)return;const messages:Record<string,string>={connected:"Googleアカウントを接続しました。",missing_scope:"Gmailの権限にチェックが入っていなかったため、接続できませんでした。もう一度接続し、Googleの確認画面で「メールの作成・送信」にチェックを入れてください。",forbidden:"この接続を行う権限がありません。",invalid:"接続の有効期限が切れました。もう一度お試しください。",failed:"Googleとの接続に失敗しました。もう一度お試しください。"};const timer=setTimeout(()=>setMessage(messages[result]??"Google接続の結果を確認できませんでした。"),0);history.replaceState(null,"",location.pathname);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(!state.data)return;const timer=setTimeout(()=>{setName(state.data!.member.name);setTitle(state.data!.member.role);setSignature(state.data!.member.signature);setOrganizationName(state.data!.organization.name);setPolicy(state.data!.mailSettings)},0);return()=>clearTimeout(timer)},[state.data]);
 useEffect(()=>{if(state.data?.member.access_role!=="owner")return;appFetch<{hasPersonalEmail:boolean;personalEmail:string|null}>("/api/owner-2fa",{method:"POST",body:JSON.stringify({action:"get_status"})}).then(r=>{if(r.personalEmail)setTwoFaRegistered(r.personalEmail)}).catch(()=>{})},[state.data?.member.access_role]);
 useEffect(()=>{if(!state.data||deviceChecked.current)return;deviceChecked.current=true;void deviceIdentity().then(async d=>{if(!state.data!.devices.some(x=>x.device_id_hash===d.hash&&!x.revoked_at)){await appFetch("/api/app",{method:"POST",body:JSON.stringify({action:"register_device",deviceHash:d.hash,label:navigator.userAgent.slice(0,120)})});await state.reload()}}).catch(e=>setMessage(e instanceof Error?e.message:"端末を登録できませんでした。"))},[state]);
 async function login(){try{const {error}=await createClient().auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent("/start?intent=member")}`}});if(error)throw error;setLoginMessage("ログインリンクを送信しました。メールを確認してください。")}catch(e){setLoginMessage(e instanceof Error?e.message:"ログインを開始できませんでした。")}}
 async function mutate(body:object){setBusy(true);setMessage("");try{await appFetch("/api/app",{method:"POST",body:JSON.stringify(body)});setMessage("保存しました。");await state.reload()}catch(e){setMessage(e instanceof Error?e.message:"保存できませんでした。")}finally{setBusy(false)}}
 async function beginGoogle(type:"organization"|"user"){setBusy(true);try{const result=await appFetch<{url:string}>("/api/google/oauth/start",{method:"POST",body:JSON.stringify({type})});location.assign(result.url)}catch(e){setMessage(e instanceof Error?e.message:"Google OAuthを開始できませんでした。");setBusy(false)}}
 async function disconnectGoogle(type:"organization"|"user"){setBusy(true);try{await appFetch("/api/google/oauth/disconnect",{method:"POST",body:JSON.stringify({type})});setMessage("Google接続を解除しました。");await state.reload()}catch(e){setMessage(e instanceof Error?e.message:"接続を解除できませんでした。")}finally{setBusy(false)}}

 async function sendTwoFaVerify(){setTwoFaStep("sending");setTwoFaMsg("");try{const r=await appFetch<{sessionId:string;maskedEmail:string}>("/api/owner-2fa",{method:"POST",body:JSON.stringify({action:"register_email",personalEmail:twoFaEmail})});setTwoFaSession(r.sessionId);setTwoFaStep("sent");setTwoFaMsg(r.maskedEmail+" に認証コードを送信しました。")}catch(e){setTwoFaMsg(e instanceof Error?e.message:"送信に失敗しました。");setTwoFaStep("idle")}}
 async function confirmTwoFaEmail(){setTwoFaStep("verifying");setTwoFaMsg("");try{await appFetch("/api/owner-2fa",{method:"POST",body:JSON.stringify({action:"confirm_email",otp:twoFaOtp,personalEmail:twoFaEmail,sessionId:twoFaSession})});setTwoFaRegistered(twoFaEmail);setTwoFaEmail("");setTwoFaOtp("");setTwoFaStep("idle");setTwoFaMsg("個人メールを登録しました。")}catch(e){setTwoFaMsg(e instanceof Error?e.message:"認証に失敗しました。");setTwoFaStep("sent")}}
 const needsLogin=Boolean(state.error?.includes("ログイン")||state.error?.includes("所属"));if(needsLogin)return <div><p className="eyebrow">Settings</p><h1 className="text-3xl font-black">設定</h1><section className="card mx-auto mt-6 max-w-lg p-6"><h2 className="flex items-center gap-2 text-xl font-black"><LogIn/>部員ログイン</h2><p className="mt-2 text-sm text-[#68746d]">招待済みの個人メールでログインします。新しい団体を作る場合は、はじめる画面へ進んでください。</p><input className="field mt-4" type="email" placeholder="member@example.jp" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn-primary mt-3 w-full" disabled={!email} onClick={login}>ログインリンクを送信</button><Link className="btn-secondary mt-3 w-full" href="/start">ログイン・団体作成画面を開く</Link>{loginMessage&&<p className="mt-3 text-sm font-bold">{loginMessage}</p>}</section></div>;
 const data=state.data,manager=data?.member.access_role==="owner"||data?.member.access_role==="admin",owner=data?.member.access_role==="owner";
 return <div><div className="flex items-end justify-between"><div><p className="eyebrow">Settings</p><h1 className="text-3xl font-black">設定</h1>{data&&<p className="mt-1 text-sm font-bold text-[#68746d]">{positionLabel[(data.member as {position?:Position}).position??"member"]??roleLabel[data.member.access_role]}</p>}</div><button className="btn-secondary" onClick={()=>createClient().auth.signOut().then(()=>location.reload())}><LogOut size={17}/>ログアウト</button></div>{state.error&&<p role="alert" className="card mt-6 p-4 text-[#a93830]">{state.error}</p>}{data&&<div className="mt-6 grid gap-5 lg:grid-cols-2">
 <section className="card p-5"><h2 className="flex items-center gap-2 font-black"><Smartphone/>自分のプロフィール</h2><div className="mt-4 grid gap-3"><label className="label">氏名<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label className="label">役職・肩書<input className="field" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="label">メール署名<textarea className="field min-h-28" value={signature} onChange={e=>setSignature(e.target.value)}/></label><code className="break-all rounded-xl bg-[#f3f6f4] p-3 text-xs">device_id: {deviceId}</code><button className="btn-primary" disabled={busy} onClick={()=>mutate({action:"update_profile",name,role:title,signature})}><Save size={18}/>変更を保存</button></div></section>
 {manager&&<GoogleCard title="組織Googleアカウント" description="Gmail送信・Drive保存・Calendar連携に必要です。ログインとは別の接続です。" connection={data.organizationGoogle} configured={data.oauthClientConfigured} busy={busy} onConnect={()=>beginGoogle("organization")} onDisconnect={()=>disconnectGoogle("organization")}/>}
 <SenderCard sender={data.sender} organizationEmail={data.organizationGoogle?.google_email??null} manager={Boolean(manager)}/>
 {(manager||data.sender.mode==="personal_email"||data.userGoogle)&&<GoogleCard title="個人Googleアカウント" description={data.sender.mode==="personal_email"?"あなたのお礼メールはこのアカウントから送信されます。":"部員個人のGmailから送信する場合に使います。通常は不要です。"} connection={data.userGoogle} configured={data.oauthClientConfigured} busy={busy} onConnect={()=>beginGoogle("user")} onDisconnect={()=>disconnectGoogle("user")}/>}
 {manager&&policy&&<section className="card p-5"><h2 className="flex items-center gap-2 font-black"><Mail/>組織メール設定</h2><div className="mt-4 grid gap-3"><label className="label">幹部の送信元<select className="field" value={policy.admin_sender_mode} onChange={e=>setPolicy({...policy,admin_sender_mode:e.target.value as MailSettings["admin_sender_mode"]})}><option value="organization_email">組織代表メール</option><option value="personal_email">個人メール</option><option value="choosable">送信時に選択</option></select></label><label className="label">部員の送信元<select className="field" value={policy.member_sender_mode} onChange={e=>setPolicy({...policy,member_sender_mode:e.target.value as MailSettings["member_sender_mode"]})}><option value="personal_email">個人メール</option><option value="organization_email">組織代表メール</option></select></label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={policy.auto_cc_organization_email} onChange={e=>setPolicy({...policy,auto_cc_organization_email:e.target.checked})}/>部員送信時に組織メールを自動CC</label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={policy.allow_member_to_disable_cc} onChange={e=>setPolicy({...policy,allow_member_to_disable_cc:e.target.checked})}/>部員本人による自動CC解除を許可</label><button className="btn-primary" disabled={busy} onClick={()=>mutate({action:"update_mail_settings",adminSenderMode:policy.admin_sender_mode,memberSenderMode:policy.member_sender_mode,autoCcOrganizationEmail:policy.auto_cc_organization_email,allowMemberToDisableCc:policy.allow_member_to_disable_cc})}>メール設定を保存</button></div></section>}
 {owner&&<section className="card p-5"><h2 className="font-black">組織設定</h2><label className="label mt-4">組織名<input className="field" value={organizationName} onChange={e=>setOrganizationName(e.target.value)}/></label><button className="btn-secondary mt-3" disabled={busy||!organizationName.trim()} onClick={()=>mutate({action:"update_organization",name:organizationName})}>組織名を保存</button>{data.organization.invite_code&&<div className="mt-4 rounded-xl border border-dashed border-[#176b45] bg-[#f1faf4] p-4"><p className="text-xs font-bold text-[#68746d]">組織コード（部員に共有してください）</p><p className="mt-1 font-mono text-2xl font-black tracking-widest text-[#176b45]">{data.organization.invite_code}</p><p className="mt-2 text-xs text-[#68746d]">このコードで入部を申請できます。代表または幹部が承認するまで、アプリの中身は見られません。</p></div>}</section>}
 {owner&&<section className="card p-5"><h2 className="flex items-center gap-2 font-black"><ShieldCheck/>オーナー二段階認証</h2><p className="mt-1 text-xs text-[#68746d]">セキュリティ強化のため、ログイン時に個人メールへの認証コード送信を有効にします。</p>{twoFaRegistered?<div className="mt-4"><div className="rounded-xl border border-[#176b45] bg-[#f1faf4] p-4"><p className="text-xs font-bold text-[#176b45]">登録済み</p><p className="mt-1 text-sm font-bold">{twoFaRegistered}</p></div><p className="mt-3 text-xs text-[#68746d]">変更する場合は新しいメールアドレスを入力してください。</p><div className="mt-2 grid gap-2"><input className="field" type="email" placeholder="新しい個人メールアドレス" value={twoFaEmail} onChange={e=>setTwoFaEmail(e.target.value)}/>{twoFaStep==="idle"&&<button className="btn-secondary" disabled={!twoFaEmail||busy} onClick={sendTwoFaVerify}>メールアドレスを変更</button>}{(twoFaStep==="sent"||twoFaStep==="verifying")&&<><input className="field text-center tracking-widest" type="text" inputMode="numeric" maxLength={6} placeholder="認証コード（6桁）" value={twoFaOtp} onChange={e=>setTwoFaOtp(e.target.value.replace(/\D/g,"").slice(0,6))}/><button className="btn-primary" disabled={twoFaOtp.length!==6||twoFaStep==="verifying"} onClick={confirmTwoFaEmail}>{twoFaStep==="verifying"?"確認中…":"認証して変更"}</button></>}</div></div>:<div className="mt-4 grid gap-2"><input className="field" type="email" placeholder="個人メールアドレス" value={twoFaEmail} onChange={e=>setTwoFaEmail(e.target.value)}/>{twoFaStep==="idle"&&<button className="btn-primary" disabled={!twoFaEmail||busy} onClick={sendTwoFaVerify}><KeyRound size={17}/>二段階認証を有効にする</button>}{twoFaStep==="sending"&&<p className="text-sm text-[#68746d]">送信しています…</p>}{(twoFaStep==="sent"||twoFaStep==="verifying")&&<><input className="field text-center tracking-widest" type="text" inputMode="numeric" maxLength={6} placeholder="認証コード（6桁）" value={twoFaOtp} onChange={e=>setTwoFaOtp(e.target.value.replace(/\D/g,"").slice(0,6))}/><button className="btn-primary" disabled={twoFaOtp.length!==6||twoFaStep==="verifying"} onClick={confirmTwoFaEmail}>{twoFaStep==="verifying"?"確認中…":"認証して登録"}</button></>}</div>}{twoFaMsg&&<p className="mt-3 text-sm font-bold">{twoFaMsg}</p>}</section>}
 {manager&&<section className="card p-5 lg:col-span-2"><h2 className="flex items-center gap-2 font-black"><UserPlus/>部員を直接追加</h2><p className="mt-1 text-xs text-[#68746d]">ここで追加した人は承認済みとして名簿に登録されます。招待コードから申請した人は、下の「入部申請」で承認してください。</p><div className="mt-4 grid gap-2 md:grid-cols-4"><input className="field" placeholder="個人メール" type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/><input className="field" placeholder="表示名" value={inviteName} onChange={e=>setInviteName(e.target.value)}/><input className="field" placeholder="肩書（任意）" value={inviteTitle} onChange={e=>setInviteTitle(e.target.value)}/><select className="field" value={inviteRole} disabled={!owner} onChange={e=>setInviteRole(e.target.value as "admin"|"member")}><option value="member">部員</option>{owner&&<option value="admin">幹部</option>}</select></div><button className="btn-primary mt-3" disabled={busy||!inviteEmail||!inviteName} onClick={()=>mutate({action:"invite_member",email:inviteEmail,name:inviteName,title:inviteTitle,accessRole:inviteRole})}><UserPlus size={18}/>追加</button></section>}
 {manager&&<MemberRoster me={data.member} members={data.members} libraryRequests={data.libraryRequests} canSuspend={data.canSuspend} busy={busy} mutate={mutate}/>}
 {manager&&<section className="card p-5 lg:col-span-2"><div className="flex justify-between"><h2 className="font-black">メールテンプレート</h2><button className="text-xs font-bold text-[#176b45]" onClick={()=>setTemplate(emptyTemplate)}>新規</button></div>{data.templates.map(t=><button key={t.id} className="mt-2 block w-full rounded-xl border p-3 text-left text-sm" onClick={()=>setTemplate({id:t.id,name:t.name,subject:t.default_subject,body:t.default_body,isDefault:t.is_default})}><strong>{t.name}</strong>{t.is_default&&<span className="ml-2 text-xs text-[#176b45]">デフォルト</span>}</button>)}<input className="field mt-3" placeholder="テンプレート名" value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})}/><input className="field mt-2" placeholder="件名" value={template.subject} onChange={e=>setTemplate({...template,subject:e.target.value})}/><textarea className="field mt-2 min-h-32" placeholder="本文" value={template.body} onChange={e=>setTemplate({...template,body:e.target.value})}/><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={template.isDefault} onChange={e=>setTemplate({...template,isDefault:e.target.checked})}/>デフォルトにする</label><button className="btn-secondary mt-3" disabled={busy||!template.name||!template.subject||!template.body} onClick={()=>mutate({action:"save_template",...template})}>テンプレートを保存</button></section>}
 </div>}{message&&<p role="status" className="card mt-4 p-4 text-sm font-bold">{message}</p>}</div>
}

function GoogleCard({title,description,connection,configured,busy,onConnect,onDisconnect}:{title:string;description?:string;connection:Connection;configured:boolean;busy:boolean;onConnect:()=>void;onDisconnect:()=>void}){return <section className="card p-5"><h2 className="flex items-center gap-2 font-black"><Cloud/>{title}</h2>{description&&<p className="mt-1 text-xs text-[#68746d]">{description}</p>}<div className="mt-4 rounded-xl border p-3"><p className="text-sm font-bold">{connection?.google_email??"未接続"}</p><p className="text-xs text-[#68746d]">{connection?.status==="active"?"接続済み":connection?"接続が切れています。「再接続」を押してください":configured?"接続してください":"Google Cloud設定が必要です"}</p></div><div className="mt-3 flex gap-2"><button className="btn-primary" disabled={busy||!configured} onClick={onConnect}><Link2 size={17}/>{connection?"再接続":"Googleと接続"}</button>{connection&&<button className="btn-danger" disabled={busy} onClick={onDisconnect}><Unlink size={17}/>接続解除</button>}</div></section>}

function SenderCard({sender,organizationEmail,manager}:{sender:SenderStatus;organizationEmail:string|null;manager:boolean}){
 const account=sender.mode==="organization_email"?"組織Googleアカウント":"個人Googleアカウント";
 const status=sender.state==="ready"?"送信できます":sender.state==="needs_reconnect"?"接続が切れています（要再接続）":"未接続です";
 const fix=sender.state==="ready"?null:sender.fixableBy==="manager"?(manager?"下の「組織Googleアカウント」で接続・再接続してください。":"オーナーか管理者に、組織Googleアカウントの接続を依頼してください。"):"下の「個人Googleアカウント」で接続・再接続してください。";
 return <section className={`card p-5 ${sender.state==="ready"?"":"border-2 border-[#cf5a50]"}`}><h2 className="flex items-center gap-2 font-black"><Mail/>あなたのお礼メールの送信元</h2><div className="mt-4 rounded-xl border p-3"><p className="text-xs text-[#68746d]">{account}</p><p className="text-sm font-bold break-all">{sender.email??"未接続"}</p><p className={`text-xs font-bold ${sender.state==="ready"?"text-[#176b45]":"text-[#a93830]"}`}>{status}</p></div>{fix&&<p className="mt-3 text-sm font-bold text-[#a93830]">{fix}</p>}{!manager&&sender.mode==="personal_email"&&organizationEmail&&<p className="mt-2 text-xs text-[#68746d]">組織アカウント（{organizationEmail}）は自動でCCに入る場合があります。</p>}</section>;
}
