"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {Cloud,Link2,LogIn,LogOut,Mail,Save,Smartphone,Unlink,UserPlus,Users} from "lucide-react";
import {appFetch,sha256Hex} from "@/lib/client-api";
import {createClientId} from "@/lib/client-crypto";
import {createClient} from "@/lib/supabase/browser";
import {useAppData} from "@/lib/use-app-data";
import type {AccessRole,MailSettings,SenderStatus} from "@/lib/organization-mail";

type Template={id:string;name:string;default_subject:string;default_body:string;is_default:boolean};
type Member={id:string;name:string;role:string;access_role:AccessRole;is_active:boolean};
type Connection={google_email:string;status:string;connected_at:string}|null;
type Settings={member:{id:string;name:string;role:string;signature:string;access_role:AccessRole};sender:SenderStatus;organization:{id:string;name:string;invite_code?:string};mailSettings:MailSettings;members:Member[];organizationGoogle:Connection;userGoogle:Connection;oauthClientConfigured:boolean;devices:Array<{device_id_hash:string;label:string;revoked_at:string|null}>;templates:Template[]};
type TemplateForm={id?:string;name:string;subject:string;body:string;isDefault:boolean};
const emptyTemplate:TemplateForm={name:"",subject:"",body:"",isDefault:false};
async function deviceIdentity(){let id=localStorage.getItem("connection-book-device-id");if(!id){id=createClientId();localStorage.setItem("connection-book-device-id",id)}return{id,hash:await sha256Hex(new Blob([id]))}}
const roleLabel:Record<AccessRole,string>={owner:"オーナー",admin:"管理者",member:"メンバー"};

export function DeviceSettings(){
 const state=useAppData<Settings>("/api/app?view=settings"),[email,setEmail]=useState(""),[loginMessage,setLoginMessage]=useState(""),[name,setName]=useState(""),[title,setTitle]=useState(""),[signature,setSignature]=useState(""),[deviceId,setDeviceId]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[template,setTemplate]=useState<TemplateForm>(emptyTemplate),[inviteEmail,setInviteEmail]=useState(""),[inviteName,setInviteName]=useState(""),[inviteTitle,setInviteTitle]=useState(""),[inviteRole,setInviteRole]=useState<"admin"|"member">("member"),[organizationName,setOrganizationName]=useState(""),[policy,setPolicy]=useState<MailSettings|null>(null);const deviceChecked=useRef(false);
 useEffect(()=>{void deviceIdentity().then(x=>setDeviceId(x.id))},[]);
 useEffect(()=>{const result=new URLSearchParams(location.search).get("google");if(!result)return;const messages:Record<string,string>={connected:"Googleアカウントを接続しました。",missing_scope:"Gmailの権限にチェックが入っていなかったため、接続できませんでした。もう一度接続し、Googleの確認画面で「メールの作成・送信」にチェックを入れてください。",forbidden:"この接続を行う権限がありません。",invalid:"接続の有効期限が切れました。もう一度お試しください。",failed:"Googleとの接続に失敗しました。もう一度お試しください。"};const timer=setTimeout(()=>setMessage(messages[result]??"Google接続の結果を確認できませんでした。"),0);history.replaceState(null,"",location.pathname);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(!state.data)return;const timer=setTimeout(()=>{setName(state.data!.member.name);setTitle(state.data!.member.role);setSignature(state.data!.member.signature);setOrganizationName(state.data!.organization.name);setPolicy(state.data!.mailSettings)},0);return()=>clearTimeout(timer)},[state.data]);
 useEffect(()=>{if(!state.data||deviceChecked.current)return;deviceChecked.current=true;void deviceIdentity().then(async d=>{if(!state.data!.devices.some(x=>x.device_id_hash===d.hash&&!x.revoked_at)){await appFetch("/api/app",{method:"POST",body:JSON.stringify({action:"register_device",deviceHash:d.hash,label:navigator.userAgent.slice(0,120)})});await state.reload()}}).catch(e=>setMessage(e instanceof Error?e.message:"端末を登録できませんでした。"))},[state]);
 async function login(){try{const {error}=await createClient().auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:`${location.origin}/auth/callback?next=${encodeURIComponent("/start?intent=member")}`}});if(error)throw error;setLoginMessage("ログインリンクを送信しました。メールを確認してください。")}catch(e){setLoginMessage(e instanceof Error?e.message:"ログインを開始できませんでした。")}}
 async function mutate(body:object){setBusy(true);setMessage("");try{await appFetch("/api/app",{method:"POST",body:JSON.stringify(body)});setMessage("保存しました。");await state.reload()}catch(e){setMessage(e instanceof Error?e.message:"保存できませんでした。")}finally{setBusy(false)}}
 async function beginGoogle(type:"organization"|"user"){setBusy(true);try{const result=await appFetch<{url:string}>("/api/google/oauth/start",{method:"POST",body:JSON.stringify({type})});location.assign(result.url)}catch(e){setMessage(e instanceof Error?e.message:"Google OAuthを開始できませんでした。");setBusy(false)}}
 async function disconnectGoogle(type:"organization"|"user"){setBusy(true);try{await appFetch("/api/google/oauth/disconnect",{method:"POST",body:JSON.stringify({type})});setMessage("Google接続を解除しました。");await state.reload()}catch(e){setMessage(e instanceof Error?e.message:"接続を解除できませんでした。")}finally{setBusy(false)}}
 const needsLogin=Boolean(state.error?.includes("ログイン")||state.error?.includes("所属"));if(needsLogin)return <div><p className="eyebrow">Settings</p><h1 className="text-3xl font-black">設定</h1><section className="card mx-auto mt-6 max-w-lg p-6"><h2 className="flex items-center gap-2 text-xl font-black"><LogIn/>部員ログイン</h2><p className="mt-2 text-sm text-[#68746d]">招待済みの個人メールでログインします。新しい団体を作る場合は、はじめる画面へ進んでください。</p><input className="field mt-4" type="email" placeholder="member@example.jp" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn-primary mt-3 w-full" disabled={!email} onClick={login}>ログインリンクを送信</button><Link className="btn-secondary mt-3 w-full" href="/start">ログイン・団体作成画面を開く</Link>{loginMessage&&<p className="mt-3 text-sm font-bold">{loginMessage}</p>}</section></div>;
 const data=state.data,manager=data?.member.access_role==="owner"||data?.member.access_role==="admin",owner=data?.member.access_role==="owner";
 return <div><div className="flex items-end justify-between"><div><p className="eyebrow">Settings</p><h1 className="text-3xl font-black">設定</h1>{data&&<p className="mt-1 text-sm font-bold text-[#68746d]">{roleLabel[data.member.access_role]}</p>}</div><button className="btn-secondary" onClick={()=>createClient().auth.signOut().then(()=>location.reload())}><LogOut size={17}/>ログアウト</button></div>{state.error&&<p role="alert" className="card mt-6 p-4 text-[#a93830]">{state.error}</p>}{data&&<div className="mt-6 grid gap-5 lg:grid-cols-2">
 <section className="card p-5"><h2 className="flex items-center gap-2 font-black"><Smartphone/>自分のプロフィール</h2><div className="mt-4 grid gap-3"><label className="label">氏名<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label className="label">役職・肩書<input className="field" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="label">メール署名<textarea className="field min-h-28" value={signature} onChange={e=>setSignature(e.target.value)}/></label><code className="rounded-xl bg-[#f3f6f4] p-3 text-xs">device_id: {deviceId}</code><button className="btn-primary" disabled={busy} onClick={()=>mutate({action:"update_profile",name,role:title,signature})}><Save size={18}/>変更を保存</button></div></section>
 {manager&&<GoogleCard title="組織Googleアカウント" description="Gmail送信・Drive保存・Calendar連携に必要です。ログインとは別の接続です。" connection={data.organizationGoogle} configured={data.oauthClientConfigured} busy={busy} onConnect={()=>beginGoogle("organization")} onDisconnect={()=>disconnectGoogle("organization")}/>}
 <SenderCard sender={data.sender} organizationEmail={data.organizationGoogle?.google_email??null} manager={Boolean(manager)}/>
 {(manager||data.sender.mode==="personal_email"||data.userGoogle)&&<GoogleCard title="個人Googleアカウント" description={data.sender.mode==="personal_email"?"あなたのお礼メールはこのアカウントから送信されます。":"部員個人のGmailから送信する場合に使います。通常は不要です。"} connection={data.userGoogle} configured={data.oauthClientConfigured} busy={busy} onConnect={()=>beginGoogle("user")} onDisconnect={()=>disconnectGoogle("user")}/>}
 {manager&&policy&&<section className="card p-5"><h2 className="flex items-center gap-2 font-black"><Mail/>組織メール設定</h2><div className="mt-4 grid gap-3"><label className="label">幹部の送信元<select className="field" value={policy.admin_sender_mode} onChange={e=>setPolicy({...policy,admin_sender_mode:e.target.value as MailSettings["admin_sender_mode"]})}><option value="organization_email">組織代表メール</option><option value="personal_email">個人メール</option></select></label><label className="label">部員の送信元<select className="field" value={policy.member_sender_mode} onChange={e=>setPolicy({...policy,member_sender_mode:e.target.value as MailSettings["member_sender_mode"]})}><option value="personal_email">個人メール</option><option value="organization_email">組織代表メール</option></select></label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={policy.auto_cc_organization_email} onChange={e=>setPolicy({...policy,auto_cc_organization_email:e.target.checked})}/>部員送信時に組織メールを自動CC</label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={policy.allow_member_to_disable_cc} onChange={e=>setPolicy({...policy,allow_member_to_disable_cc:e.target.checked})}/>部員本人による自動CC解除を許可</label><button className="btn-primary" disabled={busy} onClick={()=>mutate({action:"update_mail_settings",adminSenderMode:policy.admin_sender_mode,memberSenderMode:policy.member_sender_mode,autoCcOrganizationEmail:policy.auto_cc_organization_email,allowMemberToDisableCc:policy.allow_member_to_disable_cc})}>メール設定を保存</button></div></section>}
 {owner&&<section className="card p-5"><h2 className="font-black">組織設定</h2><label className="label mt-4">組織名<input className="field" value={organizationName} onChange={e=>setOrganizationName(e.target.value)}/></label><button className="btn-secondary mt-3" disabled={busy||!organizationName.trim()} onClick={()=>mutate({action:"update_organization",name:organizationName})}>組織名を保存</button>{data.organization.invite_code&&<div className="mt-4 rounded-xl border border-dashed border-[#176b45] bg-[#f1faf4] p-4"><p className="text-xs font-bold text-[#68746d]">組織コード（部員に共有してください）</p><p className="mt-1 font-mono text-2xl font-black tracking-widest text-[#176b45]">{data.organization.invite_code}</p><p className="mt-2 text-xs text-[#68746d]">部員はこのコードを入力して団体に参加できます。</p></div>}</section>}
 {manager&&<section className="card p-5 lg:col-span-2"><h2 className="flex items-center gap-2 font-black"><Users/>メンバー管理</h2><div className="mt-4 grid gap-2 md:grid-cols-4"><input className="field" placeholder="個人メール" type="email" value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/><input className="field" placeholder="表示名" value={inviteName} onChange={e=>setInviteName(e.target.value)}/><input className="field" placeholder="役職・肩書" value={inviteTitle} onChange={e=>setInviteTitle(e.target.value)}/><select className="field" value={inviteRole} disabled={!owner} onChange={e=>setInviteRole(e.target.value as "admin"|"member")}><option value="member">メンバー</option>{owner&&<option value="admin">管理者</option>}</select></div><button className="btn-primary mt-3" disabled={busy||!inviteEmail||!inviteName} onClick={()=>mutate({action:"invite_member",email:inviteEmail,name:inviteName,title:inviteTitle,accessRole:inviteRole})}><UserPlus size={18}/>招待・追加</button><div className="mt-5 grid gap-2">{data.members.map(item=><div key={item.id} className="flex flex-wrap items-center gap-2 rounded-xl border p-3"><div className="min-w-40 flex-1"><strong>{item.name}</strong><p className="text-xs text-[#68746d]">{item.role||"役職未設定"}・{roleLabel[item.access_role]}{!item.is_active&&"・無効"}</p></div>{owner&&item.access_role!=="owner"&&<select className="field w-auto" value={item.access_role} onChange={e=>mutate({action:"change_member_role",memberId:item.id,accessRole:e.target.value})}><option value="member">メンバー</option><option value="admin">管理者</option></select>}{owner&&item.access_role==="admin"&&<button className="btn-secondary" onClick={()=>mutate({action:"transfer_owner",memberId:item.id})}>owner移譲</button>}{item.access_role!=="owner"&&item.id!==data.member.id&&<button className="btn-danger" onClick={()=>mutate({action:"deactivate_member",memberId:item.id})}>削除</button>}</div>)}</div></section>}
 {manager&&<section className="card p-5 lg:col-span-2"><div className="flex justify-between"><h2 className="font-black">メールテンプレート</h2><button className="text-xs font-bold text-[#176b45]" onClick={()=>setTemplate(emptyTemplate)}>新規</button></div>{data.templates.map(t=><button key={t.id} className="mt-2 block w-full rounded-xl border p-3 text-left text-sm" onClick={()=>setTemplate({id:t.id,name:t.name,subject:t.default_subject,body:t.default_body,isDefault:t.is_default})}><strong>{t.name}</strong>{t.is_default&&<span className="ml-2 text-xs text-[#176b45]">デフォルト</span>}</button>)}<input className="field mt-3" placeholder="テンプレート名" value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})}/><input className="field mt-2" placeholder="件名" value={template.subject} onChange={e=>setTemplate({...template,subject:e.target.value})}/><textarea className="field mt-2 min-h-32" placeholder="本文" value={template.body} onChange={e=>setTemplate({...template,body:e.target.value})}/><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={template.isDefault} onChange={e=>setTemplate({...template,isDefault:e.target.checked})}/>デフォルトにする</label><button className="btn-secondary mt-3" disabled={busy||!template.name||!template.subject||!template.body} onClick={()=>mutate({action:"save_template",...template})}>テンプレートを保存</button></section>}
 </div>}{message&&<p role="status" className="card mt-4 p-4 text-sm font-bold">{message}</p>}</div>
}

function GoogleCard({title,description,connection,configured,busy,onConnect,onDisconnect}:{title:string;description?:string;connection:Connection;configured:boolean;busy:boolean;onConnect:()=>void;onDisconnect:()=>void}){return <section className="card p-5"><h2 className="flex items-center gap-2 font-black"><Cloud/>{title}</h2>{description&&<p className="mt-1 text-xs text-[#68746d]">{description}</p>}<div className="mt-4 rounded-xl border p-3"><p className="text-sm font-bold">{connection?.google_email??"未接続"}</p><p className="text-xs text-[#68746d]">{connection?.status==="active"?"接続済み":connection?"接続が切れています。「再接続」を押してください":configured?"接続してください":"Google Cloud設定が必要です"}</p></div><div className="mt-3 flex gap-2"><button className="btn-primary" disabled={busy||!configured} onClick={onConnect}><Link2 size={17}/>{connection?"再接続":"Googleと接続"}</button>{connection&&<button className="btn-danger" disabled={busy} onClick={onDisconnect}><Unlink size={17}/>接続解除</button>}</div></section>}

function SenderCard({sender,organizationEmail,manager}:{sender:SenderStatus;organizationEmail:string|null;manager:boolean}){
 const account=sender.mode==="organization_email"?"組織Googleアカウント":"個人Googleアカウント";
 const status=sender.state==="ready"?"送信できます":sender.state==="needs_reconnect"?"接続が切れています（要再接続）":"未接続です";
 const fix=sender.state==="ready"?null:sender.fixableBy==="manager"?(manager?"下の「組織Googleアカウント」で接続・再接続してください。":"オーナーか管理者に、組織Googleアカウントの接続を依頼してください。"):"下の「個人Googleアカウント」で接続・再接続してください。";
 return <section className={`card p-5 ${sender.state==="ready"?"":"border-2 border-[#cf5a50]"}`}><h2 className="flex items-center gap-2 font-black"><Mail/>あなたのお礼メールの送信元</h2><div className="mt-4 rounded-xl border p-3"><p className="text-xs text-[#68746d]">{account}</p><p className="text-sm font-bold break-all">{sender.email??"未接続"}</p><p className={`text-xs font-bold ${sender.state==="ready"?"text-[#176b45]":"text-[#a93830]"}`}>{status}</p></div>{fix&&<p className="mt-3 text-sm font-bold text-[#a93830]">{fix}</p>}{!manager&&sender.mode==="personal_email"&&organizationEmail&&<p className="mt-2 text-xs text-[#68746d]">組織アカウント（{organizationEmail}）は自動でCCに入る場合があります。</p>}</section>;
}
