"use client";
import {AlertTriangle,CalendarClock,CheckCircle2} from "lucide-react";
import {useState} from "react";
import {EmptyState,ErrorState,LoadingState} from "@/components/data-state";
import {appFetch} from "@/lib/client-api";
import {useAppData} from "@/lib/use-app-data";
type Item={id:string;due_at:string;content:string;status:string;calendar_status:string;calendar_error:string|null;contact:{id:string;name:string}|null;assignee:{name:string}|null};
export default function FollowupsPage(){
 const state=useAppData<{followups:Item[]}>("/api/app?view=followups"),[actionError,setActionError]=useState(""),[busyId,setBusyId]=useState("");
 async function run(id:string,action:()=>Promise<unknown>){setBusyId(id);setActionError("");try{await action();await state.reload()}catch(e){setActionError(e instanceof Error?e.message:"操作を完了できませんでした。") }finally{setBusyId("")}}
 if(state.loading)return <LoadingState/>;if(state.error)return <ErrorState message={state.error} retry={state.reload}/>;
 const now=new Date(),tomorrow=new Date(now),week=new Date(now);tomorrow.setDate(now.getDate()+1);week.setDate(now.getDate()+7);const items=state.data?.followups??[];
 const groups=[{title:"期限超過",tone:"text-[#a93830] bg-[#fff0ee]",items:items.filter(x=>x.status==="open"&&new Date(x.due_at)<now)},{title:"今日",tone:"text-[#176b45] bg-[#e2f2e8]",items:items.filter(x=>x.status==="open"&&new Date(x.due_at)>=now&&new Date(x.due_at)<tomorrow)},{title:"今週",tone:"text-[#596079] bg-[#eeeef5]",items:items.filter(x=>x.status==="open"&&new Date(x.due_at)>=tomorrow&&new Date(x.due_at)<week)},{title:"完了",tone:"text-[#68746d] bg-[#f1f3f1]",items:items.filter(x=>x.status==="done")}];
 return <div><p className="eyebrow">Follow up</p><h1 className="text-3xl font-black">フォローアップ</h1>{actionError&&<ErrorState message={actionError}/>} {!items.length?<EmptyState>フォローアップはありません</EmptyState>:<div className="mt-6 grid gap-4">{groups.filter(g=>g.items.length).map(g=><section className="card p-5" key={g.title}><h2 className="flex items-center gap-2 font-black">{g.title==="期限超過"?<AlertTriangle size={19}/>:<CalendarClock size={19}/>} {g.title}<span className={`rounded-full px-2 py-0.5 text-xs ${g.tone}`}>{g.items.length}</span></h2><div className="mt-3 grid gap-2">{g.items.map(x=><div key={x.id} className="flex flex-wrap items-center gap-3 rounded-xl border p-3 text-sm font-bold"><input aria-label={`${x.contact?.name}を完了`} type="checkbox" checked={x.status==="done"} disabled={busyId===x.id} className="size-5 accent-[#176b45]" onChange={e=>void run(x.id,()=>appFetch("/api/app",{method:"POST",body:JSON.stringify({action:"complete_followup",id:x.id,done:e.target.checked})}))}/><span className="flex-1">{x.contact?.name??"人物未設定"} — {x.content}<small className="ml-2 font-normal text-[#68746d]">{new Intl.DateTimeFormat("ja-JP",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.due_at))}</small></span>{x.status==="open"&&<button className="btn-secondary py-1 text-xs" disabled={busyId===x.id||x.calendar_status==="created"} onClick={()=>void run(x.id,()=>appFetch("/api/google/calendar",{method:"POST",body:JSON.stringify({followupId:x.id})}))}>{busyId===x.id?"処理中…":x.calendar_status==="created"?"Calendar登録済み":"Calendarに追加"}</button>}<CheckCircle2 className="text-[#9aa59e]" size={18}/>{x.calendar_error&&<p className="w-full text-xs text-[#a93830]">{x.calendar_error}</p>}</div>)}</div></section>)}</div>}</div>
}
